# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Site
title: Coolcademy
subtitle:
description:
author: Coolblue
email:
language:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://coolcademy.devneed.com
root: /
permalink: :category/:title/
tag_dir: tags
archive_dir: archives
category_dir: courses
code_dir: downloads/code

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: 0.0.0.0
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname: 

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: landscape
exclude_generator:

# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: false
  breaks: false
  smartLists: false
  smartypants: false

# Stylus
stylus:
  compress: false

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: rsync
  host: coolcademy.devneed.com
  user: coolcademy
  verbose: true
  delete: true
  root: /home/coolcademy/coolcademy.devneed.com

# Courses Information
courses:
  interviewing-course:
    title: Sollicitatie gesprekken voeren
    description: "Bij deze workshop leer je hoe je een goed sollicitatiegesprek voert voor beide partijen en de juiste informatie uit het gesprek haalt."
    longDescription: "Leer om effectief te communiceren, relevante vragen te stellen en je sollicitatiegesprek te structureren. Dit doe je in een rollenspel met een heuse trainingsacteur. Solliciteer naar een plek!"
    image: interviewingcourse.png
    startDate: "2014-10-21"
    formId: "A3EA"
    language: nl
  behind-the-scenes:
    title: Behind The Scenes
    description: "See you colleagues present the ideas behind the development of Coolblue to our mostly technical guests."
    longDescription: ""
    image: behindthescenes.png
    url: "http://www.coolblue.nl/behindthescenes"
    language: en
  codeschool:
    title: Start for new joiners IT Dev
    description: "All you need to know on your first day working for Coolblue in the IT Development team."
    longDescription: "Congratulations! You managed somehow to get a computer, an account and a password. In this course you'll learn some basics you need when starting to work for IT Development."
    image: codeschool.png
    language: en
  codecademy:
    title: PHP Done Right
    description: "Some good qualities of PHP we expect to find in our developers."
    longDescription: "Some good qualities of PHP we expect to find in our developers."
    image: codecademy.png
    language: en
  coolblue-intro:
    title: Coolblue Introduction
    description: "During this day you learn more about the why, who en how of Coolblue."
    longDescription: "The Coolblue Introduction Day is available in Dutch and English! So if you have new team members please sign them up for this immersive Coolblue experience. New at Coolblue? Then you'll be signed up automatically."
    image: "coolblueintro.png"
    startDate: "2014-11-6"
    formId: "A3EC"
    language: en
  coolblue-blauwdruk:
    title: Coolblue Blauwdruk
    description: "Voor iedereen die werkt met het merk Coolblue. Dat ben jij ook!"
    longDescription: ""
    image: blauwedag.png
    url: "https://sites.google.com/a/coolblue.nl/blueprint"
    language: nl
  writing-course:
    title: Wervend schrijven
    description: "Bij wervende teksten wil je één reactie niet: meh. Tijdens deze workshop leer je daarom de basis van wervend schrijven."
    longDescription: "Bij wervende teksten wil je één reactie niet. En dat is: meh. Tijdens deze workshop leer je daarom de basis van wervend schrijven. Aan de hand van vele aansprekende voorbeelden, ga je zelf aan de slag met je eigen teksten. Voorbereiding: neem 2 stukken wervende tekst mee die je wilt verbeteren."
    image: writingcourse.png
    startDate: "2014-11-14"
    formId: "A3F6"
    language: nl
  ux-at-coolblue:
    title: User Experience Design at Coolblue
    description: "On these pages you can find any information you need about the User Experience Design at Coolblue."
    longDescription: ""
    image: uxatcoolblue.png
    url: "https://sites.google.com/a/coolblue.nl/ux"
    language: en

  
